//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptionProcessingService.ServerMess {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestMessage", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OptionProcessingService.ServerMess.DataFeedListRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OptionProcessingService.ServerMess.HeartbeatRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OptionProcessingService.ServerMess.SubscribeRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OptionProcessingService.ServerMess.UnsubscribeRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OptionProcessingService.ServerMess.L2SubscribeRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OptionProcessingService.ServerMess.L2UnsubscribeRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OptionProcessingService.ServerMess.HistoryRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OptionProcessingService.ServerMess.AlertSubscribeRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OptionProcessingService.ServerMess.AlertUnsubscribeRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OptionProcessingService.ServerMess.BacktestGetRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OptionProcessingService.ServerMess.LoginRequest))]
    public partial class RequestMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataFeedListRequest", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class DataFeedListRequest : OptionProcessingService.ServerMess.RequestMessage {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeartbeatRequest", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class HeartbeatRequest : OptionProcessingService.ServerMess.RequestMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscribeRequest", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class SubscribeRequest : OptionProcessingService.ServerMess.RequestMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.SymbolItem SymbolField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.SymbolItem Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnsubscribeRequest", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class UnsubscribeRequest : OptionProcessingService.ServerMess.RequestMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.SymbolItem SymbolField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.SymbolItem Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="L2SubscribeRequest", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class L2SubscribeRequest : OptionProcessingService.ServerMess.RequestMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.SymbolItem SymbolField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.SymbolItem Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="L2UnsubscribeRequest", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class L2UnsubscribeRequest : OptionProcessingService.ServerMess.RequestMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.SymbolItem SymbolField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.SymbolItem Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoryRequest", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class HistoryRequest : OptionProcessingService.ServerMess.RequestMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.HistoryParameters SelectionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.HistoryParameters Selection {
            get {
                return this.SelectionField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectionField, value) != true)) {
                    this.SelectionField = value;
                    this.RaisePropertyChanged("Selection");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlertSubscribeRequest", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class AlertSubscribeRequest : OptionProcessingService.ServerMess.RequestMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlertNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BarsCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.AlertCalculateType CalculationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.Periodicity PeriodicityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScriptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.SymbolItem SymbolField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlertName {
            get {
                return this.AlertNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AlertNameField, value) != true)) {
                    this.AlertNameField = value;
                    this.RaisePropertyChanged("AlertName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BarsCount {
            get {
                return this.BarsCountField;
            }
            set {
                if ((this.BarsCountField.Equals(value) != true)) {
                    this.BarsCountField = value;
                    this.RaisePropertyChanged("BarsCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.AlertCalculateType CalculationType {
            get {
                return this.CalculationTypeField;
            }
            set {
                if ((this.CalculationTypeField.Equals(value) != true)) {
                    this.CalculationTypeField = value;
                    this.RaisePropertyChanged("CalculationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Interval {
            get {
                return this.IntervalField;
            }
            set {
                if ((this.IntervalField.Equals(value) != true)) {
                    this.IntervalField = value;
                    this.RaisePropertyChanged("Interval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.Periodicity Periodicity {
            get {
                return this.PeriodicityField;
            }
            set {
                if ((this.PeriodicityField.Equals(value) != true)) {
                    this.PeriodicityField = value;
                    this.RaisePropertyChanged("Periodicity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Script {
            get {
                return this.ScriptField;
            }
            set {
                if ((object.ReferenceEquals(this.ScriptField, value) != true)) {
                    this.ScriptField = value;
                    this.RaisePropertyChanged("Script");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.SymbolItem Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlertUnsubscribeRequest", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class AlertUnsubscribeRequest : OptionProcessingService.ServerMess.RequestMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.SymbolItem SymbolField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.SymbolItem Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BacktestGetRequest", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class BacktestGetRequest : OptionProcessingService.ServerMess.RequestMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BarsCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuyScriptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.Periodicity PeriodicityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellScriptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.SymbolItem SymbolField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BarsCount {
            get {
                return this.BarsCountField;
            }
            set {
                if ((this.BarsCountField.Equals(value) != true)) {
                    this.BarsCountField = value;
                    this.RaisePropertyChanged("BarsCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuyScript {
            get {
                return this.BuyScriptField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyScriptField, value) != true)) {
                    this.BuyScriptField = value;
                    this.RaisePropertyChanged("BuyScript");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Interval {
            get {
                return this.IntervalField;
            }
            set {
                if ((this.IntervalField.Equals(value) != true)) {
                    this.IntervalField = value;
                    this.RaisePropertyChanged("Interval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.Periodicity Periodicity {
            get {
                return this.PeriodicityField;
            }
            set {
                if ((this.PeriodicityField.Equals(value) != true)) {
                    this.PeriodicityField = value;
                    this.RaisePropertyChanged("Periodicity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SellScript {
            get {
                return this.SellScriptField;
            }
            set {
                if ((object.ReferenceEquals(this.SellScriptField, value) != true)) {
                    this.SellScriptField = value;
                    this.RaisePropertyChanged("SellScript");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.SymbolItem Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginRequest", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class LoginRequest : OptionProcessingService.ServerMess.RequestMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SymbolItem", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class SymbolItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataFeedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExchangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.Instrument TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataFeed {
            get {
                return this.DataFeedField;
            }
            set {
                if ((object.ReferenceEquals(this.DataFeedField, value) != true)) {
                    this.DataFeedField = value;
                    this.RaisePropertyChanged("DataFeed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Exchange {
            get {
                return this.ExchangeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExchangeField, value) != true)) {
                    this.ExchangeField = value;
                    this.RaisePropertyChanged("Exchange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.Instrument Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Instrument", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    public enum Instrument : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Equity = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Option = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Forex = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoryParameters", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class HistoryParameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BarsCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GenerateChartImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.Periodicity PeriodicityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.SymbolItem SymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BarsCount {
            get {
                return this.BarsCountField;
            }
            set {
                if ((this.BarsCountField.Equals(value) != true)) {
                    this.BarsCountField = value;
                    this.RaisePropertyChanged("BarsCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime From {
            get {
                return this.FromField;
            }
            set {
                if ((this.FromField.Equals(value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GenerateChartImage {
            get {
                return this.GenerateChartImageField;
            }
            set {
                if ((this.GenerateChartImageField.Equals(value) != true)) {
                    this.GenerateChartImageField = value;
                    this.RaisePropertyChanged("GenerateChartImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Interval {
            get {
                return this.IntervalField;
            }
            set {
                if ((this.IntervalField.Equals(value) != true)) {
                    this.IntervalField = value;
                    this.RaisePropertyChanged("Interval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.Periodicity Periodicity {
            get {
                return this.PeriodicityField;
            }
            set {
                if ((this.PeriodicityField.Equals(value) != true)) {
                    this.PeriodicityField = value;
                    this.RaisePropertyChanged("Periodicity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.SymbolItem Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime To {
            get {
                return this.ToField;
            }
            set {
                if ((this.ToField.Equals(value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Periodicity", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    public enum Periodicity : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Second = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Minute = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hour = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Day = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Week = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Month = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Year = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tick = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Range = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlertCalculateType", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    public enum AlertCalculateType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnTick = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnBarClose = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMessage", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OptionProcessingService.ServerMess.DataFeedListResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OptionProcessingService.ServerMess.HeartbeatResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OptionProcessingService.ServerMess.HistoryResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OptionProcessingService.ServerMess.NewTickResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OptionProcessingService.ServerMess.ErrorInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OptionProcessingService.ServerMess.AlertSubscribeResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OptionProcessingService.ServerMess.BacktestGetResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OptionProcessingService.ServerMess.L2SubscribeResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OptionProcessingService.ServerMess.LoginResponse))]
    public partial class ResponseMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataFeedListResponse", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class DataFeedListResponse : OptionProcessingService.ServerMess.ResponseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.DataFeed[] DataFeedsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.DataFeed[] DataFeeds {
            get {
                return this.DataFeedsField;
            }
            set {
                if ((object.ReferenceEquals(this.DataFeedsField, value) != true)) {
                    this.DataFeedsField = value;
                    this.RaisePropertyChanged("DataFeeds");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeartbeatResponse", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class HeartbeatResponse : OptionProcessingService.ServerMess.ResponseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoryResponse", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class HistoryResponse : OptionProcessingService.ServerMess.ResponseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.Bar[] BarsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChartImageDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TailField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.Bar[] Bars {
            get {
                return this.BarsField;
            }
            set {
                if ((object.ReferenceEquals(this.BarsField, value) != true)) {
                    this.BarsField = value;
                    this.RaisePropertyChanged("Bars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChartImageData {
            get {
                return this.ChartImageDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ChartImageDataField, value) != true)) {
                    this.ChartImageDataField = value;
                    this.RaisePropertyChanged("ChartImageData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Tail {
            get {
                return this.TailField;
            }
            set {
                if ((this.TailField.Equals(value) != true)) {
                    this.TailField = value;
                    this.RaisePropertyChanged("Tail");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewTickResponse", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class NewTickResponse : OptionProcessingService.ServerMess.ResponseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.Tick[] TickField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.Tick[] Tick {
            get {
                return this.TickField;
            }
            set {
                if ((object.ReferenceEquals(this.TickField, value) != true)) {
                    this.TickField = value;
                    this.RaisePropertyChanged("Tick");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorInfo", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class ErrorInfo : OptionProcessingService.ServerMess.ResponseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlertSubscribeResponse", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class AlertSubscribeResponse : OptionProcessingService.ServerMess.ResponseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.Alert AlertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlertNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.Alert Alert {
            get {
                return this.AlertField;
            }
            set {
                if ((object.ReferenceEquals(this.AlertField, value) != true)) {
                    this.AlertField = value;
                    this.RaisePropertyChanged("Alert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlertName {
            get {
                return this.AlertNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AlertNameField, value) != true)) {
                    this.AlertNameField = value;
                    this.RaisePropertyChanged("AlertName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BacktestGetResponse", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class BacktestGetResponse : OptionProcessingService.ServerMess.ResponseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.BacktestInformationItem[] InformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.SymbolItem SymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.BacktestTradeItem[] TradesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.BacktestInformationItem[] Information {
            get {
                return this.InformationField;
            }
            set {
                if ((object.ReferenceEquals(this.InformationField, value) != true)) {
                    this.InformationField = value;
                    this.RaisePropertyChanged("Information");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.SymbolItem Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.BacktestTradeItem[] Trades {
            get {
                return this.TradesField;
            }
            set {
                if ((object.ReferenceEquals(this.TradesField, value) != true)) {
                    this.TradesField = value;
                    this.RaisePropertyChanged("Trades");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="L2SubscribeResponse", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class L2SubscribeResponse : OptionProcessingService.ServerMess.ResponseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.Level2Data Level2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.Level2Data Level2 {
            get {
                return this.Level2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Level2Field, value) != true)) {
                    this.Level2Field = value;
                    this.RaisePropertyChanged("Level2");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponse", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class LoginResponse : OptionProcessingService.ServerMess.ResponseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataFeed", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class DataFeed : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.ExchangeInfo[] ExchangesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.ExchangeInfo[] Exchanges {
            get {
                return this.ExchangesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExchangesField, value) != true)) {
                    this.ExchangesField = value;
                    this.RaisePropertyChanged("Exchanges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExchangeInfo", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class ExchangeInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.SymbolItem[] SymbolsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.SymbolItem[] Symbols {
            get {
                return this.SymbolsField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolsField, value) != true)) {
                    this.SymbolsField = value;
                    this.RaisePropertyChanged("Symbols");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bar", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class Bar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CloseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HighField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double OpenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double VolumeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Close {
            get {
                return this.CloseField;
            }
            set {
                if ((this.CloseField.Equals(value) != true)) {
                    this.CloseField = value;
                    this.RaisePropertyChanged("Close");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double High {
            get {
                return this.HighField;
            }
            set {
                if ((this.HighField.Equals(value) != true)) {
                    this.HighField = value;
                    this.RaisePropertyChanged("High");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Low {
            get {
                return this.LowField;
            }
            set {
                if ((this.LowField.Equals(value) != true)) {
                    this.LowField = value;
                    this.RaisePropertyChanged("Low");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Open {
            get {
                return this.OpenField;
            }
            set {
                if ((this.OpenField.Equals(value) != true)) {
                    this.OpenField = value;
                    this.RaisePropertyChanged("Open");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Volume {
            get {
                return this.VolumeField;
            }
            set {
                if ((this.VolumeField.Equals(value) != true)) {
                    this.VolumeField = value;
                    this.RaisePropertyChanged("Volume");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tick", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class Tick : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AskSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BidSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.SymbolItem SymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double VolumeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Ask {
            get {
                return this.AskField;
            }
            set {
                if ((this.AskField.Equals(value) != true)) {
                    this.AskField = value;
                    this.RaisePropertyChanged("Ask");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AskSize {
            get {
                return this.AskSizeField;
            }
            set {
                if ((this.AskSizeField.Equals(value) != true)) {
                    this.AskSizeField = value;
                    this.RaisePropertyChanged("AskSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Bid {
            get {
                return this.BidField;
            }
            set {
                if ((this.BidField.Equals(value) != true)) {
                    this.BidField = value;
                    this.RaisePropertyChanged("Bid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BidSize {
            get {
                return this.BidSizeField;
            }
            set {
                if ((this.BidSizeField.Equals(value) != true)) {
                    this.BidSizeField = value;
                    this.RaisePropertyChanged("BidSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.SymbolItem Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Volume {
            get {
                return this.VolumeField;
            }
            set {
                if ((this.VolumeField.Equals(value) != true)) {
                    this.VolumeField = value;
                    this.RaisePropertyChanged("Volume");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alert", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class Alert : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.SymbolItem SymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.SymbolItem Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BacktestInformationItem", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class BacktestInformationItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BacktestTradeItem", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class BacktestTradeItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateString {
            get {
                return this.DateStringField;
            }
            set {
                if ((object.ReferenceEquals(this.DateStringField, value) != true)) {
                    this.DateStringField = value;
                    this.RaisePropertyChanged("DateString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Level2Data", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class Level2Data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.Level2Item[] AsksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.Level2Item[] BidsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OptionProcessingService.ServerMess.SymbolItem SymbolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.Level2Item[] Asks {
            get {
                return this.AsksField;
            }
            set {
                if ((object.ReferenceEquals(this.AsksField, value) != true)) {
                    this.AsksField = value;
                    this.RaisePropertyChanged("Asks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.Level2Item[] Bids {
            get {
                return this.BidsField;
            }
            set {
                if ((object.ReferenceEquals(this.BidsField, value) != true)) {
                    this.BidsField = value;
                    this.RaisePropertyChanged("Bids");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionProcessingService.ServerMess.SymbolItem Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Level2Item", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class Level2Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarketMakerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MarketMaker {
            get {
                return this.MarketMakerField;
            }
            set {
                if ((object.ReferenceEquals(this.MarketMakerField, value) != true)) {
                    this.MarketMakerField = value;
                    this.RaisePropertyChanged("MarketMaker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataServerException", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
    [System.SerializableAttribute()]
    public partial class DataServerException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServerMess.IWCFService", CallbackContract=typeof(OptionProcessingService.ServerMess.IWCFServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/Login", ReplyAction="http://tempuri.org/IWCFService/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OptionProcessingService.ServerMess.DataServerException), Action="http://tempuri.org/IWCFService/LoginDataServerExceptionFault", Name="DataServerException", Namespace="http://schemas.datacontract.org/2004/07/CommonObjects")]
        OptionProcessingService.ServerMess.LoginResponse Login(OptionProcessingService.ServerMess.LoginRequest message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsTerminating=true, IsInitiating=false, Action="http://tempuri.org/IWCFService/LogOut")]
        void LogOut();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsInitiating=false, Action="http://tempuri.org/IWCFService/MessageIn")]
        void MessageIn(OptionProcessingService.ServerMess.RequestMessage message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/MessageOut")]
        void MessageOut(OptionProcessingService.ServerMess.ResponseMessage message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFServiceChannel : OptionProcessingService.ServerMess.IWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFServiceClient : System.ServiceModel.DuplexClientBase<OptionProcessingService.ServerMess.IWCFService>, OptionProcessingService.ServerMess.IWCFService {
        
        public WCFServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public WCFServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public WCFServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public OptionProcessingService.ServerMess.LoginResponse Login(OptionProcessingService.ServerMess.LoginRequest message) {
            return base.Channel.Login(message);
        }
        
        public void LogOut() {
            base.Channel.LogOut();
        }
        
        public void MessageIn(OptionProcessingService.ServerMess.RequestMessage message) {
            base.Channel.MessageIn(message);
        }
    }
}
